# Generated by Django 4.1.5 on 2023-01-31 22:14

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
